default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: runteq
  password: password

development:
  <<: *default
  database: circle_test

test:
  <<: *default
  database: circle_test
